name: todo
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  createDocs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo 
        uses: actions/checkout@v2
      - name: Install nodejs  
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: run app
        run: npm ci
        run: run build
        run: npm run export
        
 
    
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: out
        env:
          GITHUB_TOKEN: ${{ secrets.TODO }}
